name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '^1.20.0'

      - name: Run tests
        run: |
          mkdir -p pkg/admin/ui/dist && touch pkg/admin/ui/dist/test
          go test ./... -race -coverprofile=coverage.txt -covermode=atomic